FROM kalibr-hw290:doc-20261009
ARG BUILD_JOBS=2
USER root
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libyaml-cpp-dev python3-yaml python3-numpy python3-scipy python3-matplotlib
RUN mkdir -p /allan_ws/src && \
    git clone https://github.com/ori-drs/allan_variance_ros.git /allan_ws/src/allan_variance_ros && \
    git -C /allan_ws/src/allan_variance_ros checkout 1d54b602ee7f2ba0427865d63afe4945d913ed24
RUN /bin/bash -c 'source /catkin_ws/devel/setup.bash && cd /allan_ws && \
    catkin init && catkin config --extend /catkin_ws/devel \
    --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    catkin build allan_variance_ros --no-status --jobs "$BUILD_JOBS"'
ENTRYPOINT ["/bin/bash"]
