cmake_minimum_required(VERSION 3.8)
project(ov_hw290)

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(OpenCV REQUIRED COMPONENTS core imgproc calib3d aruco)
find_package(Qt5 REQUIRED COMPONENTS Widgets)

add_executable(stereo_splitter src/stereo_splitter.cpp)
ament_target_dependencies(stereo_splitter rclcpp sensor_msgs)
target_include_directories(stereo_splitter PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(stereo_splitter ${OpenCV_LIBS})
target_compile_features(stereo_splitter PUBLIC cxx_std_17)
target_compile_options(stereo_splitter PRIVATE -O2 -Wall -Wextra)

add_executable(hw290_imu src/hw290_imu.cpp)
ament_target_dependencies(hw290_imu rclcpp sensor_msgs)
target_include_directories(hw290_imu PRIVATE include)
target_compile_features(hw290_imu PUBLIC cxx_std_17)
target_compile_options(hw290_imu PRIVATE -O2 -Wall -Wextra)

add_executable(calibration_screen src/calibration_screen.cpp)
ament_target_dependencies(calibration_screen rclcpp sensor_msgs)
target_include_directories(calibration_screen PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(calibration_screen ${OpenCV_LIBS} Qt5::Widgets)
target_compile_features(calibration_screen PUBLIC cxx_std_17)
target_compile_options(calibration_screen PRIVATE -O2 -Wall -Wextra)

install(TARGETS hw290_imu stereo_splitter calibration_screen DESTINATION lib/${PROJECT_NAME})
ament_package()
